### ISSUE TITLE
Changes needed for current version of angular material

### ISSUE THREAD

**Issue by rayearth42** [GustavoCostaW/ngc-float-button#5]
Please change the MaterialModule import to MatIconModule.  The use of MaterialModule has been deprecated in the current version of angular material and causes an error.

ERROR in D:/data/workspace/XXX/src/main/webapp/node_modules/ngc-float-button/ind
ex.ts (3,10): Module '"D:/data/workspace/IML/src/main/webapp/node_modules/@angul
ar/material/material"' has no exported member 'MaterialModule'.

Additionally, change md-icon to mat-icon as the md prefix has been deprecated as well.

**Comment by GustavoCostaW** [comment]
I will fix this problem in this weekend, thank you.

**Comment by mordka** [comment]
We couldn't wait any longer :) Please find my PR #7

**Comment by GustavoCostaW** [comment]
Hey @rayearth42 , unfortunately, I was pretty sick because of this I took so long to fix that, sorry and I just published the new version and it's compatible with angular >= 4.4.4 and >= angular material beta 12, enjoy.

just run `npm install --save ngc-float-button`

You can check the demo with the latest version. http://bit.ly/2yIya2f
