### ISSUE TITLE
No longer works with latest version of angular material 

### ISSUE THREAD

**Issue by fennekit** [GustavoCostaW/ngc-float-button#6]
In the latest versions angular material MaterialModule is no longer present. Including the package fails with

ERROR in project/node_modules/ngc-float-button/index.ts (3,10): Module '"project/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.

**Comment by GustavoCostaW** [comment]
I will fix this problem in this weekend, thank you.

**Comment by adrian23** [comment]
Any news ?

**Comment by hblanken** [comment]
Encountered the same issues - no action @GustavoCostaW so we probably need to remove this fab :(

**Comment by mordka** [comment]
Thanks @GustavoCostaW for this fantastic package. Please find our PR #7 which resolves this.
To all waiting for the merge you can use upgraded package by installing it this way `npm install -S ngc-float-button/settings`

**Comment by GustavoCostaW** [comment]
Hey @fennekit @adrian23  @hblanken @mordka , unfortunately, I was pretty sick because of this I took so long to fix that, sorry and I just published the new version and it's compatible with angular >= 4.4.4 and >= angular material beta 12, enjoy.

just run `npm install --save ngc-float-button`

You can check the demo with the latest version. http://bit.ly/2yIya2f
